version: "3"

services:
  web:
    build: 
      context: ./movie_api
      dockerfile: Dockerfile
    command: bash -c "python /movie_api/manage.py migrate && python /movie_api/manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./movie_api/:/movie_api/
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:13
    ports:
      - 5432:5432
    volumes:
      - ./docker/postgres/docker-pg-vol/data:/var/lib/postgresql/data
      - ./docker/postgres/init/initData.sql:/docker-entrypoint-initdb.d/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    healthcheck:
          test: ["CMD-SHELL", "pg_isready -U postgres || exit 1"]
          interval: 10s
          timeout: 5s
          retries: 5
volumes:
  pg-data:
    driver: local
 