# Generated by Django 4.1.7 on 2023-05-02 16:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MovieInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("movie_title", models.CharField(max_length=100)),
                ("director", models.TextField(null=True)),
                ("actor", models.TextField(null=True)),
                ("deploy", models.DateField(null=True)),
                ("genre", models.CharField(max_length=100, null=True)),
                ("country", models.CharField(max_length=100, null=True)),
                ("age", models.CharField(max_length=100, null=True)),
                ("running", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="TheaterInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("theater_type", models.CharField(max_length=100)),
                ("theater_name", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=100)),
                ("start_time", models.TimeField(default=datetime.time(0, 0))),
                (
                    "movie_title",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="api.movieinfo",
                    ),
                ),
            ],
        ),
    ]
